# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNf4HaH2oobNKderUNK35jZvSMVo4hQ8
"""

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

bot = ChatBot(
    'NIA',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    database_uri='sqlite:///database.sqlite3',
    logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.TimeLogicAdapter'
    ]
)


trainer = ListTrainer(bot)


trainer.train([
    'Olá',
    'Olá! Eu sou a NIA, sua assistente virtual acadêmica da UNICET. Como posso te ajudar hoje?'
])

trainer.train([
    'matrícula',
    'O período de matrícula abre no início de cada semestre. Você pode fazer pelo portal acadêmico (https://unicet.edu.br/) ou presencialmente na secretaria acadêmica. O atendimento ocorre de Segunda - Sexta: 8:00 AM a 22:00 PM.'
])

trainer.train([
    'rematrícula',
    'A rematrícula é feita online pelo portal do aluno. Caso tenha pendências financeiras, verifique com o setor financeiro no telefone: (86) 3333-2222.'
])

trainer.train([
    'horários de aula',
    'Os horários de aula ficam disponíveis no portal do aluno. Se precisar, a Central do Aluno pode ajudar: (86) 9 9981-6961.'
])

trainer.train([
    'calendário acadêmico',
    'O calendário acadêmico com datas de provas, feriados e início das aulas está disponível no site oficial da instituição. Abra o site (https://unicet.edu.br/) -> Vá para a aba Serviços -> Clique em Calendário Acadêmico.'
])

trainer.train([
    'notas',
    'As notas podem ser acessadas pelo portal do aluno, na aba “Boletim”. Para dúvidas, entre em contato com a Central do Aluno: (86) 9 9981-6961.'
])

trainer.train([
    'boletim',
    'Seu boletim completo fica disponível no portal do aluno. Para atendimento presencial, procure a Central do Aluno: (86) 9 9981-6961.'
])

trainer.train([
    'documentos acadêmicos',
    'Você pode solicitar histórico escolar, declaração de matrícula e atestados presencialmente na secretaria acadêmica. Ou entre em contato com a Central do Aluno no telefone: (86) 9 9981-6961.'
])

trainer.train([
    'financeiro',
    'Questões financeiras como mensalidades, boletos e renegociações devem ser tratadas no setor financeiro. Entre em contato com a Central do Aluno: (86) 9 9981-6961'
])

trainer.train([
    'suporte',
    'Para suporte técnico ou dúvidas gerais, entre em contato com o setor de TI. Para contato: (86) 3333-3333 | Email: suporteti@unicet.edu.br.'
])

trainer.train([
    'Olá',
    'Olá! Eu sou a NIA, sua assistente virtual acadêmica da UNICET. Como posso te ajudar hoje?'
])

trainer.train([
    'Qual seu nome?',
    'Eu sou a NIA, sua assistente virtual acadêmica.'
])

trainer.train([
    'o que NIA significa?',
    'NIA significa Núcleo de Inteligência Acadêmica. Fui criada para apoiar você em assuntos da faculdade.'
])

trainer.train([
    'quais documentos necessários para matrícula?',
    'Para matrícula, geralmente são necessários: RG, CPF, histórico escolar do ensino médio, comprovante de residência e foto 3x4.'
])

trainer.train([
    'quais documentos necessários para rematrícula?',
    'A rematrícula normalmente só exige estar em dia com as mensalidades e confirmar online no portal do aluno.'
])

trainer.train([
    'biblioteca',
    'A biblioteca funciona de segunda a sexta, das 8h às 20h. Para empréstimos, apresente sua carteirinha de estudante. Em caso de dúvidas, ligue (86) 3333-4444.'
])

trainer.train([
    'estágio',
    'O setor de estágio fica no Bloco D, sala 401. Para se inscrever, leve RG, CPF e histórico escolar. Mais informações pelo email: estagios@unicet.edu.br.'
])

trainer.train([
    'carteirinha',
    'A primeira via da carteirinha é gratuita. Para segunda via, é cobrada uma taxa na tesouraria. Retire sua carteirinha na secretaria acadêmica.'
])

trainer.train([
    'trancamento',
    'O trancamento de disciplina ou curso deve ser solicitado na secretaria acadêmica até a 4ª semana de aula. Documentos: RG e formulário preenchido.'
])

trainer.train([
    'atividades extracurriculares',
    'Você pode participar de monitoria, iniciação científica e ligas acadêmicas. Acesse o portal do aluno na aba “Atividades”.'
])

trainer.train([
    'eventos acadêmicos',
    'Acompanhe os eventos da instituição em www.unicet.edu.br/eventos ou no mural da secretaria acadêmica.'
])

trainer.train([
    'wifi',
    'A rede Wi-Fi da instituição é "UNICET_ALUNOS". O login e senha são os mesmos do portal acadêmico.'
])

trainer.train([
    'ead',
    'A plataforma EAD pode ser acessada em www.unicet.edu.br/ead. Use seu RA e senha do portal do aluno.'
])


print("Digite 'sair' para encerrar a conversa.")

while True:
    print("\nEscolha uma opção:")
    print("1. Matrícula/Rematrícula")
    print("2. Horários de aula")
    print("3. Calendário acadêmico")
    print("4. Notas e Boletim")
    print("5. Documentos acadêmicos")
    print("6. Atendimento financeiro")
    print("7. Suporte geral")
    print("8. Falar livremente com a NIA")

    escolha = input("Digite o número da opção: ")

    if escolha.lower() == 'sair':
        print("NIA: Até logo!")
        break

    if escolha == '1':
        print("NIA: Você deseja saber sobre matrícula ou rematrícula?")
        msg = input("Você: ")
        resposta = bot.get_response(msg)
        print("NIA:", resposta)

    elif escolha == '2':
        resposta = bot.get_response("horários de aula")
        print("NIA:", resposta)

    elif escolha == '3':
        resposta = bot.get_response("calendário acadêmico")
        print("NIA:", resposta)

    elif escolha == '4':
        resposta = bot.get_response("boletim")
        print("NIA:", resposta)

    elif escolha == '5':
        resposta = bot.get_response("documentos acadêmicos")
        print("NIA:", resposta)

    elif escolha == '6':
        resposta = bot.get_response("financeiro")
        print("NIA:", resposta)

    elif escolha == '7':
        resposta = bot.get_response("suporte")
        print("NIA:", resposta)

    elif escolha == '8':
        print("NIA: Agora você pode conversar livremente comigo. Digite 'voltar' para retornar ao menu.")
        while True:
            msg = input("Você: ")
            if msg.lower() in ['voltar', 'menu']:
                print("NIA: Voltando ao menu principal...")
                break
            elif msg.lower() == 'sair':
                print("NIA: Até logo!")
                break
            resposta = bot.get_response(msg)
            print("NIA:", resposta)

    else:
        print("NIA: Opção inválida. Por favor, escolha entre 1 e 8.")